/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soft252cw;

/**
 *
 * @author Oliver
 */
public class SecretaryHome extends javax.swing.JFrame {

    /**
     * Creates new form SecretaryHome
     */
    
    public Hospital hospital;
    
    public SecretaryHome(Hospital hospital) {
        initComponents();
        this.hospital = hospital;
    }
    
    public void onLoad(){
         displayPatientsToApprove();
         displayPatientsToRemove();
         displayPatientsWithAppointments();
    }
    
    public void displayPatientsToApprove(){
        cbApprovePatient.removeAllItems();
        for (HospitalPerson person : hospital.people) {
            if (person.getID().charAt(0) == 'P') {
                Patient pat = (Patient) person;
                if (pat.isApproved() == false) {
                    cbApprovePatient.addItem(pat.getName()+ " "+ pat.getSurname());
                }
            }
        }
    }
 
    public void displayPatientsToRemove() {
        cbRemovePatient.removeAllItems();
        for (HospitalPerson person : hospital.people) {
            if (person.getID().charAt(0) == 'P') {
                Patient pat = (Patient) person;
                if (pat.isRemoveRequest() == true) {
                    cbRemovePatient.addItem(pat.getName() + " " + pat.getSurname());
                }
            }
        }
    }
    
    public void displayPatientsWithAppointments(){
        cbPatients.removeAllItems();
        for (HospitalPerson person : hospital.people) {
            if (person.getID().charAt(0) == 'P') {   
                cbPatients.addItem(person.getName()+" "+ person.getSurname());
                Patient pat = (Patient) person;
                displayAppointmentsToCreate(pat);
            }
        } 
    }
    
    public void displayAppointmentsToCreate(Patient pat){
        cbAppointments.removeAllItems();
        for (int i = 0; i < pat.getAppointment().size(); i++) {
            if (pat.getAppointment().get(i).isApprovesd() == false) {
                cbAppointments.addItem(pat.getAppointment().get(i).getDoctorName()
                        + " on " + pat.getAppointment().get(i).getDate());

            }
        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbApprovePatient = new javax.swing.JComboBox<>();
        btnApprove = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbRemovePatient = new javax.swing.JComboBox<>();
        btnRemove = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbPatients = new javax.swing.JComboBox<>();
        cbAppointments = new javax.swing.JComboBox<>();
        btnCreateAppointment = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Patient accounts to be approved :");

        btnApprove.setText("Approve");

        jLabel2.setText("Patient accounts to be removed :");

        btnRemove.setText("Remove");

        jLabel3.setText("Patient Requests for appointmets:");

        btnCreateAppointment.setText("Create Appointment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateAppointment)
                    .addComponent(cbAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbApprovePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbRemovePatient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnApprove)
                            .addComponent(btnRemove))))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbApprovePatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApprove))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbRemovePatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPatients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateAppointment)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Approve Patients", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Medicine", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnCreateAppointment;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cbAppointments;
    private javax.swing.JComboBox<String> cbApprovePatient;
    private javax.swing.JComboBox<String> cbPatients;
    private javax.swing.JComboBox<String> cbRemovePatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
