/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soft252cw;

/**
 *
 * @author Oliver
 */
public class SecretaryHome extends javax.swing.JFrame {

    /**
     * Creates new form SecretaryHome
     */
    
    public Hospital hospital;
    public Patient currentPatient;
    
    public SecretaryHome(Hospital hospital) {
        initComponents();
        this.hospital = hospital;
    }
    
    public void onLoad(){
        lblApproveOutput.setText("");
        lblRemoveOutput.setText("");
        lblAppointmentsOutput.setText("");
         displayPatientsToApprove();
         displayPatientsToRemove();
         displayPatientsWithAppointments();
    }
    
    public void displayPatientsToApprove(){
        cbApprovePatient.removeAllItems();
        for (HospitalPerson person : hospital.people) {
            if (person.getID().charAt(0) == 'P') {
                Patient pat = (Patient) person;
                if (pat.isApproved() == false) {
                    cbApprovePatient.addItem(pat.getName()+ " "+ pat.getSurname());
                }
            }
        }
    }
 
    public void displayPatientsToRemove() {
        cbRemovePatient.removeAllItems();    
        
        
        for (HospitalPerson person : hospital.people) {
            if (person.getID().charAt(0) == 'P') {
                Patient pat = (Patient) person;
                if (pat.isRemoveRequest() == true) {
                    cbRemovePatient.addItem(pat.getName() + " " + pat.getSurname());
                }
            }
        }
    }
    
    public void displayPatientsWithAppointments() {
        cbPatients.removeAllItems();

        System.out.println("Here ");
        for (HospitalPerson person : hospital.people) {
            if (person.getID().charAt(0) == 'P') {
                System.out.println("Here 1");
                Patient pat = (Patient) person;
                for (int i = 0; i < pat.getAppointment().size(); i++) {
                    System.out.println("Here 2");
                    if (pat.getAppointment().get(i).isApprovesd() == false) {
                        System.out.println("Here 3");
                        cbPatients.addItem(person.getName() + " " + person.getSurname());

                        // a name is added twice if have two appointments to approve.
                    }
                }
            }
        }
        displayAppointmentsToCreate();
    }

    public void displayAppointmentsToCreate() {
        txtAreaAppointment.setText("");

        getCurrentPatient(cbPatients.getSelectedItem().toString());

        for (int i = 0; i < currentPatient.getAppointment().size(); i++) {
            if (currentPatient.getAppointment().get(i).isApprovesd() == false) {
                txtAreaAppointment.append(currentPatient.getAppointment().get(i).getDoctorName()
                        + " on " + currentPatient.getAppointment().get(i).getDate() + "\n");
            }
        }
    }

    public void getCurrentPatient(String selectedPatient) {
        String PatientName = selectedPatient;

        hospital.people.forEach((_item) -> {

            boolean nameTest = PatientName.equals(_item.getName() + " " + _item.getSurname());

            if (nameTest == true) {
                currentPatient = (Patient) _item;
            }
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbApprovePatient = new javax.swing.JComboBox<>();
        btnApprove = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbRemovePatient = new javax.swing.JComboBox<>();
        btnRemove = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbPatients = new javax.swing.JComboBox<>();
        btnCreateAppointment = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAppointment = new javax.swing.JTextArea();
        lblApproveOutput = new javax.swing.JLabel();
        lblRemoveOutput = new javax.swing.JLabel();
        lblAppointmentsOutput = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Patient accounts to be approved :");

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        jLabel2.setText("Patient accounts to be removed :");

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jLabel3.setText("Patients with Requests for appointmets:");

        cbPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPatientsActionPerformed(evt);
            }
        });

        btnCreateAppointment.setText("Create Appointment");
        btnCreateAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAppointmentActionPerformed(evt);
            }
        });

        jLabel5.setText("Requested Appointments:");

        txtAreaAppointment.setColumns(20);
        txtAreaAppointment.setRows(5);
        jScrollPane1.setViewportView(txtAreaAppointment);

        lblApproveOutput.setText("jLabel6");

        lblRemoveOutput.setText("jLabel6");

        lblAppointmentsOutput.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCreateAppointment)
                        .addGap(18, 18, 18)
                        .addComponent(lblAppointmentsOutput))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbApprovePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbRemovePatient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnApprove)
                                .addGap(18, 18, 18)
                                .addComponent(lblApproveOutput))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRemove)
                                .addGap(18, 18, 18)
                                .addComponent(lblRemoveOutput)))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbApprovePatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApprove)
                    .addComponent(lblApproveOutput))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbRemovePatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove)
                    .addComponent(lblRemoveOutput))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPatients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateAppointment)
                    .addComponent(lblAppointmentsOutput))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Approve Patients", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Medicine", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPatientsActionPerformed
        if (cbPatients.getSelectedItem() == null) {
            System.out.println("oopsie");
        } else {
            for (HospitalPerson person : hospital.people) {
                if (cbPatients.getSelectedItem().equals(person.getName() + " " + person.getSurname())) {
                    displayAppointmentsToCreate();
                }
            }
        }     
    }//GEN-LAST:event_cbPatientsActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        if (cbApprovePatient.getSelectedItem() != null) {
            String patientName = cbApprovePatient.getSelectedItem().toString();

            for (HospitalPerson person : hospital.people) {
                if (patientName.equals(person.getName() + " " + person.getSurname())) {
                    Patient pat = (Patient) person;
                    pat.setApproved(true);
                }
            }
            displayPatientsToApprove();
        }else{
            lblApproveOutput.setText("No accounts to approve.");
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if(cbRemovePatient.getSelectedItem() != null){
            String patientName = cbRemovePatient.getSelectedItem().toString();

            for (int i = 0; i < hospital.people.size(); i++) {
                if (patientName.equals(hospital.people.get(i).getName() + " " + hospital.people.get(i).getSurname())) {
                    Patient pat = (Patient) hospital.people.get(i);
                    pat.setRemoveRequest(true);
                    hospital.people.remove(hospital.people.get(i));
                }
            }
            displayPatientsToRemove();
        }else{
            lblRemoveOutput.setText("No accounts to remove");
        }        

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCreateAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAppointmentActionPerformed
        if(cbPatients.getSelectedItem() != null){
            for (int i = 0; i < currentPatient.getAppointment().size(); i++) {
                if (currentPatient.getAppointment().get(i).isApprovesd() == false) {
                    currentPatient.getAppointment().get(i).setApprovesd(true);
                }
            }
            displayPatientsWithAppointments();
        }else{
            lblAppointmentsOutput.setText("No appointments to approve");
        }
    }//GEN-LAST:event_btnCreateAppointmentActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnCreateAppointment;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cbApprovePatient;
    private javax.swing.JComboBox<String> cbPatients;
    private javax.swing.JComboBox<String> cbRemovePatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAppointmentsOutput;
    private javax.swing.JLabel lblApproveOutput;
    private javax.swing.JLabel lblRemoveOutput;
    private javax.swing.JTextArea txtAreaAppointment;
    // End of variables declaration//GEN-END:variables
}
